<script setup lang="ts">
import { ref, computed } from 'vue'
import MdiWizardHat from '@/components/icons/MdiWizardHat.vue'
import TablerLogicNand from '@/components/icons/TablerLogicNand.vue'
import TextAi from '@/components/TextAi.vue'
import Loading from '@/components/Loading.vue'
import RequestGrid from '@/components/RequestGrid.vue'
import PreviewButton from '@/components/PreviewButton.vue'
import PredButton from '@/components/PredButton.vue'
import { usePanels } from '@/stores/panels'
import DragEditWindow1 from '@/components/DragEditWindow1.vue'
import { useKeys } from '@/stores/keys'
import { useRoute } from 'vue-router'
import { useList } from '@/stores/list'
import { useQuasar } from 'quasar'
import { useTitle } from '@vueuse/core'
import { useStorage } from '@vueuse/core'

const app = useStorage('app', localStorage)
const title = useTitle('Папки: ' + app.value.label)

const list = useList()
const route = useRoute()

const currentFolder = computed(() => {
	return list.lists.find((item) => item.id === route.params.id)
})

const mykeys = useKeys()

const main = ref(true)

const toggleMain = () => {
	main.value = !main.value
}

const panels = usePanels()

const startRight = async () => {
	panels.setPreview(true)
}

const startLeft = async () => {
	panels.setPred(true)
}

const stopRight = async () => {
	panels.setPreview(false)
}

const stopLeft = async () => {
	panels.setPred(false)
}

const fullscreen = ref(false)

// const toggleFull = () => {
// 	if (fullscreen.value == false) {
// 		panels.setPred(false)
// 		panels.setPreview(false)
// 	} else {
// 		panels.setPred(true)
// 		panels.setPreview(true)
// 	}
// 	fullscreen.value = !fullscreen.value
// }

const calcPageClass = computed(() => {
	if (panels.pred && panels.preview) return 'collapsedB'
	if (panels.pred) return 'collapsedL'
	if (panels.preview) return 'collapsedR'
	return ''
})

const isShaking = ref(false)
const isShaking1 = ref(false)

const startPred = () => {
	if (!panels.pred) startLeft()
	else {
		isShaking.value = true
		setTimeout(() => {
			isShaking.value = false
		}, 1000)
	}
}
const isSearching = ref(false)

const $q = useQuasar()
const checkStartSearch = () => {
	if (mykeys.hasParameters.length == 0) {
		isSearching.value = true
	} else {
		if (panels.preview) {
			isShaking1.value = true
			setTimeout(() => {
				isShaking1.value = false
				$q.notify({
					icon: 'mdi-check-bold',
					color: 'positive',
					message: 'Заполните форму запроса справа',
				})
			}, 1000)
		} else startRight()
	}
	mykeys.removeDragWindow()
}
</script>

<template lang="pug">
q-page(padding
	:class='calcPageClass'
	)
	PredButton(@activate='startLeft' @stop='stopLeft' :class="{'shake-horizontal': isShaking}")
	.editor
		.top(@click='toggleMain')
			.zg Настройка папки "{{ currentFolder?.label }}"
			.q-gutter-x-sm
				q-btn(flat round dense color="primary") 
					q-icon(v-if='main' name="mdi-wizard-hat" color="primary")
					q-icon(v-else name="mdi-logic-nand" color="primary")
				q-btn.q-ml-md(flat round dense icon="mdi-content-duplicate" color="primary" @click="") 
				q-btn.q-ml-md(flat round dense color="primary" @click="toggleFull") 
					q-icon(v-if='fullscreen' name="mdi-fullscreen-exit" color="primary")
					q-icon(v-else name="mdi-fullscreen" color="primary")

		transition(name="slide-bottom" mode="out-in")
			RequestGrid(v-if='main' @button='checkStartSearch' @open='startRight')
			TextAi(v-else)

		Loading(@startPred='startPred' v-model:poisk='isSearching' button :folder='currentFolder?.label')

	PreviewButton(@activate='startRight' @stop='stopRight' :class="{'shake-horizontal': isShaking1}" @search='isSearching = true')

	DragEditWindow1(v-model="mykeys.isDragWindow")
</template>

<style scoped lang="scss">
.q-page {
	display: grid;
	grid-template-columns: 50px 1fr 50px;
	column-gap: 0.5rem;
	transition: all 0.2s ease;
	&.collapsedL {
		grid-template-columns: 390px 1fr 50px;
	}
	&.collapsedR {
		grid-template-columns: 50px 1fr 390px;
	}
	&.collapsedB {
		grid-template-columns: 390px 1fr 390px;
	}
}

.editor {
	// width: 100%;
	margin-top: 0;
	padding: 0;
	background: var(--bgLight);
	position: relative;
}

.top {
	width: 100%;
}

.zg {
	font-size: 1.3rem;
	font-weight: 500;
}

.ic {
	font-size: 1.5rem;
}
.test {
	width: 48px;
	height: 48px;
	background: #fff;
	box-shadow: var(--shad0);
	border-radius: 24px;
	position: absolute;
	top: 0;
	left: -58px;
	text-align: center;
	cursor: pointer;
}

.shake-horizontal {
	-webkit-animation: shake-horizontal 0.5s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
	animation: shake-horizontal 0.5s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2025-4-1 16:15:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes shake-horizontal {
	0%,
	100% {
		-webkit-transform: translateX(0);
		transform: translateX(0);
	}
	10%,
	30%,
	50%,
	70% {
		-webkit-transform: translateX(-10px);
		transform: translateX(-10px);
	}
	20%,
	40%,
	60% {
		-webkit-transform: translateX(10px);
		transform: translateX(10px);
	}
	80% {
		-webkit-transform: translateX(8px);
		transform: translateX(8px);
	}
	90% {
		-webkit-transform: translateX(-8px);
		transform: translateX(-8px);
	}
}
@keyframes shake-horizontal {
	0%,
	100% {
		-webkit-transform: translateX(0);
		transform: translateX(0);
	}
	10%,
	30%,
	50%,
	70% {
		-webkit-transform: translateX(-10px);
		transform: translateX(-10px);
	}
	20%,
	40%,
	60% {
		-webkit-transform: translateX(10px);
		transform: translateX(10px);
	}
	80% {
		-webkit-transform: translateX(8px);
		transform: translateX(8px);
	}
	90% {
		-webkit-transform: translateX(-8px);
		transform: translateX(-8px);
	}
}
</style>
