const events: MyEvent[] = [
	{
		id: 1,
		sideId: 'Event_1t7b10m',
		role: 'Инициатор',
		name: 'Создал заявку',
		fio: 'Орлов П.С.',
		start: new Date(2025, 8, 29),
		end: new Date(2025, 8, 29),
		type: 'point',
		className: 'start',
	},
	{
		id: 2,
		sideId: 'Activity_13ysreu',
		role: 'Руководитель',
		name: 'Согласовать заявку',
		fio: 'Соколов С.П.',
		start: new Date(2025, 8, 30),
		end: new Date(2025, 9, 2),
		type: 'range',
	},
	{
		id: 3,
		sideId: 'Activity_0kpt2qn',
		role: 'Инициатор',
		fio: 'Орлов П.С.',
		name: 'Исправить заявку',
		start: new Date(2025, 9, 2),
		end: new Date(2025, 9, 6, 13, 0, 0),
		type: 'range',
	},
	{
		id: 4,
		sideId: 'Activity_13ysreu',
		role: 'Руководитель',
		name: 'Согласовать заявку',
		fio: 'Соколов С.П.',
		start: new Date(2025, 9, 7),
		end: new Date(2025, 9, 10),
		type: 'range',
	},
	{
		id: 5,
		sideId: 'Activity_0vjxzxe',
		role: 'Рассматривающий',
		fio: 'Воронин A.A.',
		name: 'Рассмотреть заявку',
		start: new Date(2025, 9, 10),
		end: new Date(),
		type: 'range',
		current: true,
	},
]

export { events }
