import { uid } from 'quasar'
import { Kind, Newkind } from '@/types/enum'

const operators = [
	{
		id: '1',
		text: 'И',
		text1: '',
		text2: '',
		hidden: false,
		type: 0,
		selected: false,
		drag: true,
		drop: true,
		icon: 'mdi-gate-and',
		fields: [],
		synparents: [],
		syn: [],
		children: [],
	},
	{
		id: '2',
		text: 'ИЛИ',
		text1: '',
		text2: '',
		hidden: false,
		type: 0,
		typ: true,
		selected: false,
		drag: true,
		drop: true,
		icon: 'mdi-gate-or',
		fields: [],
		synparents: [],
		syn: [],
		children: [],
	},
]
const fields = [
	{
		id: uid(),
		text: 'Документ',
		hidden: false,
		type: 1,
		selected: false,
		drag: false,
		drop: false,
		open: true,
		children: [
			{
				id: uid(),
				parents: ['Документ'],
				text: 'Тема',
				type: 1,
				hidden: false,
				open: true,
				selected: false,
				drag: true,
				drop: false,
				kind: Kind.String,
				newkind: Newkind.String,
				inp: true,
				common: true,
			},
			{
				id: 'ooo',
				parents: ['Документ'],
				text: 'Номер',
				kind: Kind.Num,
				newkind: Newkind.Num,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				inp: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Документ'],
				text: 'Дата регистрации',
				kind: Kind.Date,
				newkind: Newkind.Datetime,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				date: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Документ'],
				text: 'Регистратор',
				kind: Kind.Man,
				newkind: Newkind.Id,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				man: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Документ'],
				text: 'Содержание',
				kind: Kind.Text,
				newkind: Newkind.String,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				inp: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Документ'],
				text: 'Дата документа',
				kind: Kind.Date,
				newkind: Newkind.Datetime,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				date: true,
				common: true,
			},
			// doc begin ************************
			{
				type: 1,
				id: uid(),
				parents: ['Документ'],
				text: 'Адресаты',
				hidden: false,
				selected: false,
				drag: false,
				children: [
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Номер',
						kind: Kind.Num,
						newkind: Newkind.Num,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Дата регистрации',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Регистратор',
						kind: Kind.Man,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Подготовил',
						kind: Kind.Man,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Предмет договора',
						kind: Kind.Text,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Организация',
						kind: Kind.Man,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Дата документа',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Ответственный',
						kind: Kind.Man,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Подписывают',
						kind: Kind.Man,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Организация контрагент',
						kind: Kind.Org,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Адресаты', 'Организация контрагент'],
								text: 'Контактное лицо',
								kind: Kind.Man,
								newkind: Newkind.Id,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Адресаты', 'Организация контрагент'],
								text: 'Организация',
								kind: Kind.String,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Адресаты', 'Организация контрагент'],
								text: 'Телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Адресаты', 'Организация контрагент'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Адресаты', 'Организация контрагент'],
								text: 'ИНН',
								kind: Kind.String,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Адресаты', 'Организация контрагент'],
								text: 'ОГРН',
								kind: Kind.String,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Адресаты', 'Организация контрагент'],
								text: 'БИК',
								kind: Kind.String,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: false,
							},
						],
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Состояние',
						kind: Kind.Status,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						state: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Заданиe',
						kind: Kind.Link,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Адресаты'],
						text: 'Группа заданий',
						kind: Kind.Link,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
				],
			},

			{
				type: 1,
				id: uid(),
				parents: ['Документ'],
				text: 'Бизнес-процессы',
				hidden: false,
				selected: false,
				drag: false,
				children: [
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Тема',
						kind: Kind.String,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Номер',
						kind: Kind.Num,
						newkind: Newkind.Num,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Дата регистрации',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Регистратор',
						kind: Kind.Man,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Подготовил',
						kind: Kind.Man,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Содержание',
						kind: Kind.Text,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Согласующие',
						kind: Kind.Man,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Подписывают',
						kind: Kind.Man,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Организация получатель',
						kind: Kind.Org,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Бизнес-процессы', 'Организация получатель'],
								text: 'Контактное лицо',
								kind: Kind.Man,
								newkind: Newkind.Id,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Бизнес-процессы', 'Организация получатель'],
								text: 'Организация',
								kind: Kind.String,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Бизнес-процессы', 'Организация получатель'],
								text: 'Телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Бизнес-процессы', 'Организация получатель'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Состояние',
						kind: Kind.Status,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						state: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Заданиe',
						kind: Kind.Link,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Бизнес-процессы'],
						text: 'Группа заданий',
						kind: Kind.Link,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
				],
			},
			{
				type: 1,
				id: uid(),
				parents: ['Документ'],
				text: 'Данные о подписанте',
				hidden: false,
				selected: false,
				drag: false,
				children: [
					{
						id: uid(),
						parents: ['Документ', 'Данные о подписанте'],
						text: 'Тема',
						kind: Kind.String,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Данные о подписанте'],
						text: 'Номер',
						kind: Kind.Num,
						newkind: Newkind.Num,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Данные о подписанте'],
						text: 'Дата регистрации',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Данные о подписанте'],
						text: 'Регистратор',
						kind: Kind.Man,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Данные о подписанте'],
						text: 'Содержание',
						kind: Kind.Text,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Данные о подписанте'],
						text: 'Исх.номер',
						kind: Kind.Num,
						newkind: Newkind.Num,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Данные о подписанте'],
						text: 'Дата документа',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Данные о подписанте'],
						text: 'Организация отправитель',
						kind: Kind.Org,
						newkind: Newkind.Id,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Данные о подписанте', 'Организация отправитель'],
								text: 'Контактное лицо',
								kind: Kind.Man,
								newkind: Newkind.Id,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Данные о подписанте', 'Организация отправитель'],
								text: 'Организация',
								kind: Kind.String,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Данные о подписанте', 'Организация отправитель'],
								text: 'Телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
							{
								id: uid(),
								parents: ['Документ', 'Данные о подписанте', 'Организация отправитель'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								type: 1,
								hidden: false,
								selected: false,
								drag: true,
								man: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Документ', 'Данные о подписанте'],
						text: 'Состояние',
						kind: Kind.Status,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
						state: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Данные о подписанте'],
						text: 'Заданиe',
						kind: Kind.Link,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Документ', 'Данные о подписанте'],
						text: 'Группа заданий',
						kind: Kind.Link,
						newkind: Newkind.String,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
				],
			},
		],
	},
	{
		id: uid(),
		text: 'Задание',
		hidden: false,
		type: 1,
		selected: false,
		drag: false,
		children: [
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Название',
				kind: Kind.String,
				newkind: Newkind.String,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				inp: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Срок исполнения',
				kind: Kind.Date,
				newkind: Newkind.Datetime,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				date: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Дата контроля',
				kind: Kind.Date,
				newkind: Newkind.Datetime,
				date: true,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Дата отправки',
				kind: Kind.Date,
				newkind: Newkind.Datetime,
				date: true,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Важность',
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Автор',
				kind: Kind.Man,
				newkind: Newkind.Id,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				man: true,
				common: true,
				children: [
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Фамилия',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Имя',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Отчество',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Дата рождения',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						drag: true,
						common: true,
						date: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Должность',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
						man: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Руководитель',
						kind: Kind.Man,
						newkind: Newkind.Id,
						drag: true,
						common: true,
						man: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Местный телефон',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Домашний телефон',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Факс',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Номер паспорта',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
						inp: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Паспорт выдан',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
						date: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Комната',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Сотовый телефон',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'IP телефон',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Значимость',
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Email',
						kind: Kind.Email,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Организация',
						kind: Kind.Org,
						newkind: Newkind.Id,
						drag: true,
						common: true,
						man: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Автор'],
						text: 'Является руководителем',
						kind: Kind.Bool,
						newkind: Newkind.Bool,
						drag: true,
						common: true,
						ruk: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Содержание',
				kind: Kind.Text,
				newkind: Newkind.String,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				inp: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Докумeнт',
				kind: Kind.Link,
				newkind: Newkind.String,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Исполнитель',
				kind: Kind.Man,
				newkind: Newkind.Id,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				man: true,
				common: true,
				children: [
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Исполнитель'],
						text: 'Фамилия',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Исполнитель'],
						text: 'Имя',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Исполнитель'],
						text: 'Отчество',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Исполнитель'],
						text: 'Дата рождения',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
						date: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Исполнитель'],
						text: 'Должность',
						kind: Kind.Text,
						newkind: Newkind.String,
						man: true,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Исполнитель'],
						text: 'Руководитель',
						kind: Kind.Man,
						newkind: Newkind.Id,
						drag: true,
						common: true,
						man: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Исполнитель'],
						text: 'Значимость',
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Исполнитель'],
						text: 'Email',
						kind: Kind.Email,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Исполнитель'],
						text: 'Организация',
						kind: Kind.Org,
						newkind: Newkind.Id,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Исполнитель'],
						text: 'Является руководителем',
						kind: Kind.Bool,
						newkind: Newkind.Bool,
						drag: true,
						common: true,
						ruk: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Состояние ',
				kind: Kind.Status,
				newkind: Newkind.String,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				state: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Подчиненные группы заданий',
				kind: Kind.Link,
				newkind: Newkind.String,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Подчиненные задания',
				kind: Kind.Link,
				newkind: Newkind.String,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Контролер',
				kind: Kind.Man,
				newkind: Newkind.Id,
				man: true,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				common: true,
				children: [
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Контролер'],
						text: 'Фамилия',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Контролер'],
						text: 'Имя',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Контролер'],
						text: 'Отчество',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Контролер'],
						text: 'Дата рождения',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						common: true,
						date: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Контролер'],
						text: 'Должность',
						kind: Kind.Text,
						newkind: Newkind.String,
						man: true,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Контролер'],
						text: 'Руководитель',
						kind: Kind.Man,
						newkind: Newkind.Id,
						drag: true,
						common: true,
						man: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Контролер'],
						text: 'Значимость',
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Контролер'],
						text: 'Email',
						kind: Kind.Email,
						newkind: Newkind.String,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Контролер'],
						text: 'Организация',
						kind: Kind.Org,
						newkind: Newkind.Id,
						drag: true,
						common: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['Задание', 'Контролер'],
						text: 'Является руководителем',
						kind: Kind.Bool,
						newkind: Newkind.Bool,
						drag: true,
						common: true,
						ruk: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Длительность фактическая',
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Завершено позже срока',
				kind: Kind.Bool,
				newkind: Newkind.Bool,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				ruk: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Задание ответственного исполнителя',
				kind: Kind.Bool,
				newkind: Newkind.Bool,
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Данные УПД',
				hidden: false,
				type: 1,
				selected: false,
				drag: false,
				children: [
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Название',
						kind: Kind.String,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Срок исполнения',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Дата контроля',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						date: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Дата отправки',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						date: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Важность',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Автор',
						kind: Kind.Man,
						newkind: Newkind.Id,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Фамилия',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Имя',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Отчество',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Дата рождения',
								kind: Kind.Date,
								newkind: Newkind.Datetime,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Должность',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Руководитель',
								kind: Kind.Man,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Местный телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Домашний телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Факс',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Номер паспорта',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								inp: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Паспорт выдан',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Комната',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Сотовый телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'IP телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Организация',
								kind: Kind.Org,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Автор'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								newkind: Newkind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Содержание',
						kind: Kind.Text,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Докумeнт',
						kind: Kind.Link,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Исполнитель',
						kind: Kind.Man,
						newkind: Newkind.Id,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Исполнитель'],
								text: 'Фамилия',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Исполнитель'],
								text: 'Имя',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Исполнитель'],
								text: 'Отчество',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Исполнитель'],
								text: 'Дата рождения',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Исполнитель'],
								text: 'Должность',
								kind: Kind.Text,
								newkind: Newkind.String,
								man: true,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Исполнитель'],
								text: 'Руководитель',
								kind: Kind.Man,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Исполнитель'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Исполнитель'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Исполнитель'],
								text: 'Организация',
								kind: Kind.Org,
								newkind: Newkind.Id,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Исполнитель'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								newkind: Newkind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Состояние ',
						kind: Kind.Status,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Подчиненные группы заданий',
						kind: Kind.Link,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Подчиненные задания',
						kind: Kind.Link,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Контролер',
						kind: Kind.Man,
						newkind: Newkind.Id,
						man: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Контролер'],
								text: 'Фамилия',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Контролер'],
								text: 'Имя',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Контролер'],
								text: 'Отчество',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Контролер'],
								text: 'Дата рождения',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Контролер'],
								text: 'Должность',
								kind: Kind.Text,
								newkind: Newkind.String,
								man: true,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Контролер'],
								text: 'Руководитель',
								kind: Kind.Man,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Контролер'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Контролер'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Контролер'],
								text: 'Организация',
								kind: Kind.Org,
								newkind: Newkind.Id,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Данные УПД', 'Контролер'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								newkind: Newkind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Длительность фактическая',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Завершено позже срока',
						kind: Kind.Bool,
						newkind: Newkind.Bool,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						ruk: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Данные УПД'],
						text: 'Задание ответственного исполнителя',
						kind: Kind.Bool,
						newkind: Newkind.Bool,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Секция 1',
				hidden: false,
				type: 1,
				selected: false,
				drag: false,
				children: [
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Название',
						kind: Kind.String,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Срок исполнения',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Дата контроля',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						date: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Дата отправки',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						date: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Важность',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Автор',
						kind: Kind.Man,
						newkind: Newkind.Id,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Фамилия',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Имя',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Отчество',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Дата рождения',
								kind: Kind.Date,
								newkind: Newkind.Datetime,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Должность',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Руководитель',
								kind: Kind.Man,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Местный телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Домашний телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Факс',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Номер паспорта',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								inp: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Паспорт выдан',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Комната',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Сотовый телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'IP телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Организация',
								kind: Kind.Org,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Автор'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								newkind: Newkind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Содержание',
						kind: Kind.Text,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Докумeнт',
						kind: Kind.Link,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Исполнитель',
						kind: Kind.Man,
						newkind: Newkind.Id,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Исполнитель'],
								text: 'Фамилия',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Исполнитель'],
								text: 'Имя',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Исполнитель'],
								text: 'Отчество',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Исполнитель'],
								text: 'Дата рождения',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Исполнитель'],
								text: 'Должность',
								kind: Kind.Text,
								newkind: Newkind.String,
								man: true,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Исполнитель'],
								text: 'Руководитель',
								kind: Kind.Man,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Исполнитель'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Исполнитель'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Исполнитель'],
								text: 'Организация',
								kind: Kind.Org,
								newkind: Newkind.Id,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Исполнитель'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								newkind: Newkind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Состояние ',
						kind: Kind.Status,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Подчиненные группы заданий',
						kind: Kind.Link,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Подчиненные задания',
						kind: Kind.Link,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Контролер',
						kind: Kind.Man,
						newkind: Newkind.Id,
						man: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Контролер'],
								text: 'Фамилия',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Контролер'],
								text: 'Имя',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Контролер'],
								text: 'Отчество',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Контролер'],
								text: 'Дата рождения',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Контролер'],
								text: 'Должность',
								kind: Kind.Text,
								newkind: Newkind.String,
								man: true,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Контролер'],
								text: 'Руководитель',
								kind: Kind.Man,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Контролер'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Контролер'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Контролер'],
								text: 'Организация',
								kind: Kind.Org,
								newkind: Newkind.Id,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 1', 'Контролер'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								newkind: Newkind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Длительность фактическая',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 1'],
						text: 'Завершено позже срока',
						kind: Kind.Bool,
						newkind: Newkind.Bool,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						ruk: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Секция 2',
				hidden: false,
				type: 1,
				selected: false,
				drag: false,
				children: [
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Название',
						kind: Kind.String,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Срок исполнения',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						date: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Дата контроля',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						date: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Дата отправки',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						date: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Важность',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Автор',
						kind: Kind.Man,
						newkind: Newkind.Id,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Фамилия',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Имя',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Отчество',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Дата рождения',
								kind: Kind.Date,
								newkind: Newkind.Datetime,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Должность',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Руководитель',
								kind: Kind.Man,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Местный телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Домашний телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Факс',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Номер паспорта',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								inp: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Паспорт выдан',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Комната',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Сотовый телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'IP телефон',
								kind: Kind.Phone,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Организация',
								kind: Kind.Org,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Автор'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								newkind: Newkind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Содержание',
						kind: Kind.Text,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Докумeнт',
						kind: Kind.Link,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Исполнитель',
						kind: Kind.Man,
						newkind: Newkind.Id,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						man: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Исполнитель'],
								text: 'Фамилия',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Исполнитель'],
								text: 'Имя',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Исполнитель'],
								text: 'Отчество',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Исполнитель'],
								text: 'Дата рождения',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Исполнитель'],
								text: 'Должность',
								kind: Kind.Text,
								newkind: Newkind.String,
								man: true,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Исполнитель'],
								text: 'Руководитель',
								kind: Kind.Man,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Исполнитель'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Исполнитель'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Исполнитель'],
								text: 'Организация',
								kind: Kind.Org,
								newkind: Newkind.Id,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Исполнитель'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								newkind: Newkind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Состояние ',
						kind: Kind.Status,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Подчиненные группы заданий',
						kind: Kind.Link,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Подчиненные задания',
						kind: Kind.Link,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Контролер',
						kind: Kind.Man,
						newkind: Newkind.Id,
						man: true,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						children: [
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Контролер'],
								text: 'Фамилия',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Контролер'],
								text: 'Имя',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Контролер'],
								text: 'Отчество',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Контролер'],
								text: 'Дата рождения',
								kind: Kind.Text,
								newkind: Newkind.String,
								drag: true,
								date: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Контролер'],
								text: 'Должность',
								kind: Kind.Text,
								newkind: Newkind.String,
								man: true,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Контролер'],
								text: 'Руководитель',
								kind: Kind.Man,
								newkind: Newkind.Id,
								drag: true,
								man: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Контролер'],
								text: 'Значимость',
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Контролер'],
								text: 'Email',
								kind: Kind.Email,
								newkind: Newkind.String,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Контролер'],
								text: 'Организация',
								kind: Kind.Org,
								newkind: Newkind.Id,
								drag: true,
							},
							{
								type: 1,
								hidden: false,
								selected: false,
								id: uid(),
								parents: ['Задание', 'Секция 2', 'Контролер'],
								text: 'Является руководителем',
								kind: Kind.Bool,
								newkind: Newkind.Bool,
								drag: true,
								ruk: true,
							},
						],
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Длительность фактическая',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Завершено позже срока',
						kind: Kind.Bool,
						newkind: Newkind.Bool,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						ruk: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Задание ответственного исполнителя',
						kind: Kind.Bool,
						newkind: Newkind.Bool,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Инициатор',
						kind: Kind.Man,
						newkind: Newkind.Id,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						man: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Этап согласования',
						kind: Kind.String,
						newkind: Newkind.String,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Секция 2'],
						text: 'Цикл согласования',
						kind: Kind.Num,
						newkind: Newkind.Num,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
				],
			},
		],
	},
	{
		id: uid(),
		text: 'Группа заданий',
		hidden: false,
		type: 1,
		selected: false,
		drag: false,
		children: [
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Тема',
				kind: Kind.String,
				newkind: Newkind.String,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				inp: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Отправлено',
				kind: Kind.Date,
				newkind: Newkind.Datetime,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				date: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Срок исполнения',
				kind: Kind.Date,
				newkind: Newkind.Datetime,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				date: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Автор',
				kind: Kind.Man,
				newkind: Newkind.Id,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				man: true,
				children: [
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Фамилия',
						kind: Kind.Text,
						newkind: Newkind.String,
						man: true,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Имя',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Отчество',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Дата рождения',
						kind: Kind.Text,
						newkind: Newkind.String,
						date: true,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Должность',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						man: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Руководитель',
						kind: Kind.Man,
						newkind: Newkind.Id,
						drag: true,
						man: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Местный телефон',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Домашний телефон',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Факс',
						newkind: Newkind.String,
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Номер паспорта',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						inp: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Паспорт выдан',
						newkind: Newkind.String,
						kind: Kind.Text,
						drag: true,
						date: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Комната',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Сотовый телефон',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'IP телефон',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Значимость',
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Email',
						kind: Kind.Email,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Организация',
						kind: Kind.Org,
						newkind: Newkind.Id,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Автор'],
						text: 'Является руководителем',
						kind: Kind.Bool,
						newkind: Newkind.Bool,
						drag: true,
						ruk: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Содержание ',
				kind: Kind.Text,
				newkind: Newkind.String,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				inp: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Мое виртуальное поле',
				kind: Kind.Virtual,
				newkind: Newkind.Virtual,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				inp: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Докумeнт',
				kind: Kind.Link,
				newkind: Newkind.String,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Исполнители',
				kind: Kind.Table,
				newkind: Newkind.Table,
				man: true,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				children: [
					{
						id: uid(),
						parents: ['ГЗ', 'Исполнители'],
						text: 'Id',
						kind: Kind.Table,
						newkind: Newkind.Table,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['ГЗ', 'Исполнители'],
						text: 'Фамилия',
						kind: Kind.Table,
						newkind: Newkind.Table,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['ГЗ', 'Исполнители'],
						text: 'Имя',
						kind: Kind.Table,
						newkind: Newkind.Table,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['ГЗ', 'Исполнители'],
						text: 'Отчество',
						kind: Kind.Table,
						newkind: Newkind.Table,
						type: 1,
						hidden: false,
						selected: false,
						drag: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Состояние ',
				kind: Kind.Status,
				newkind: Newkind.String,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Подчиненные задания',
				kind: Kind.Link,
				newkind: Newkind.String,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Контролер',
				kind: Kind.Man,
				newkind: Newkind.Id,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				man: true,
				children: [
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Фамилия',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Имя',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Отчество',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Дата рождения',
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						drag: true,
						date: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Должность',
						kind: Kind.Text,
						newkind: Newkind.String,
						man: true,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Руководитель',
						kind: Kind.Man,
						newkind: Newkind.Id,
						drag: true,
						man: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Местный телефон',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Домашний телефон',
						newkind: Newkind.String,
						kind: Kind.Phone,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Факс',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Номер паспорта',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
						inp: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Паспорт выдан',
						newkind: Newkind.String,
						kind: Kind.Text,
						drag: true,
						date: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Комната',
						kind: Kind.Text,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Сотовый телефон',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'IP телефон',
						kind: Kind.Phone,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Значимость',
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Email',
						kind: Kind.Email,
						newkind: Newkind.String,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Организация',
						kind: Kind.Org,
						newkind: Newkind.Id,
						drag: true,
					},
					{
						type: 1,
						hidden: false,
						selected: false,
						id: uid(),
						parents: ['ГЗ', 'Контролер'],
						text: 'Является руководителем',
						kind: Kind.Bool,
						newkind: Newkind.Bool,
						drag: true,
						ruk: true,
					},
				],
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Тип',
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
			},
		],
	},
	{
		id: uid(),
		text: 'Квартальная цель',
		hidden: false,
		type: 1,
		selected: false,
		drag: false,
		children: [
			{
				id: uid(),
				text: 'Дата регистрации',
				hidden: false,
				parents: ['Квартальная цель'],
				type: 1,
				selected: false,
				kind: Kind.Date,
				newkind: Newkind.Datetime,
				drag: true,
				date: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Регистратор',
				hidden: false,
				parents: ['Квартальная цель'],
				type: 1,
				selected: false,
				kind: Kind.Man,
				newkind: Newkind.Id,
				drag: true,
				man: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Сотрудник',
				hidden: false,
				parents: ['Квартальная цель'],
				type: 1,
				selected: false,
				kind: Kind.Man,
				newkind: Newkind.Id,
				drag: true,
				man: true,
				children: [],
			},
			{
				id: 'foo',
				text: 'Год',
				parents: ['Квартальная цель'],
				hidden: false,
				type: 1,
				kind: Kind.Num,
				newkind: Newkind.Num,
				selected: false,
				drag: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Квартал',
				parents: ['Квартальная цель'],
				hidden: false,
				type: 1,
				kind: Kind.Num,
				newkind: Newkind.Num,
				selected: false,
				drag: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Сумма факта',
				parents: ['Квартальная цель'],
				hidden: false,
				type: 1,
				kind: Kind.Num,
				newkind: Newkind.Digit,
				selected: false,
				drag: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Сумма весов',
				parents: ['Квартальная цель'],
				hidden: false,
				type: 1,
				kind: Kind.Num,
				newkind: Newkind.Digit,
				selected: false,
				drag: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Состояние',
				parents: ['Квартальная цель'],
				hidden: false,
				type: 1,
				kind: Kind.Status,
				newkind: Newkind.String,
				selected: false,
				drag: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Цели',
				parents: ['Квартальная цель'],
				hidden: false,
				type: 1,
				kind: Kind.String,
				newkind: Newkind.String,
				selected: false,
				drag: true,
				children: [
					{
						id: uid(),
						text: 'Критерий достижения',
						parents: ['Квартальная цель', 'Цели'],
						hidden: false,
						type: 1,
						kind: Kind.String,
						newkind: Newkind.String,
						selected: false,
						drag: true,
						children: [],
					},
					{
						id: uid(),
						text: 'Плановая дата выполнения',
						parents: ['Квартальная цель', 'Цели'],
						hidden: false,
						type: 1,
						kind: Kind.Date,
						newkind: Newkind.Datetime,
						selected: false,
						drag: true,
						date: true,
						children: [],
					},
					{
						id: uid(),
						text: 'Вес',
						parents: ['Квартальная цель', 'Цели'],
						hidden: false,
						type: 1,
						kind: Kind.Num,
						newkind: Newkind.Digit,
						selected: false,
						drag: true,
						children: [],
					},
					{
						id: uid(),
						text: 'Факт',
						parents: ['Квартальная цель', 'Цели'],
						hidden: false,
						type: 1,
						kind: Kind.Num,
						newkind: Newkind.Digit,
						selected: false,
						drag: true,
						children: [],
					},
				],
			},
		],
	},
	{
		id: uid(),
		text: 'Командировка',
		hidden: false,
		type: 1,
		selected: false,
		drag: false,
		children: [
			{
				id: uid(),
				text: 'Номер',
				hidden: false,
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Num,
				newkind: Newkind.Num,
				drag: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Дата регистрации',
				hidden: false,
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Date,
				newkind: Newkind.Datetime,
				drag: true,
				date: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Регистратор',
				hidden: false,
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Man,
				newkind: Newkind.Id,
				drag: true,
				man: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Командируемые',
				hidden: false,
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Man,
				newkind: Newkind.Id,
				drag: true,
				man: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Цель поездки',
				hidden: false,
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Text,
				newkind: Newkind.String,
				drag: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Ответственный',
				hidden: false,
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Man,
				newkind: Newkind.Id,
				drag: true,
				man: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Дата отъезда',
				hidden: false,
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Date,
				newkind: Newkind.Datetime,
				drag: true,
				date: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Куда',
				parents: ['Командировка'],
				hidden: false,
				type: 1,
				kind: Kind.String,
				newkind: Newkind.String,
				selected: false,
				drag: true,
				children: [
					{
						id: uid(),
						text: 'Регион',
						parents: ['Командировка', 'Куда'],
						hidden: false,
						type: 1,
						kind: Kind.String,
						newkind: Newkind.String,
						selected: false,
						drag: true,
						children: [],
					},
					{
						id: uid(),
						text: 'Город',
						parents: ['Командировка', 'Куда'],
						hidden: false,
						type: 1,
						kind: Kind.String,
						newkind: Newkind.String,
						selected: false,
						drag: true,
						children: [],
					},
				],
			},
			{
				id: uid(),
				text: 'Организация',
				parents: ['Командировка'],
				hidden: false,
				type: 1,
				kind: Kind.Org,
				newkind: Newkind.Id,
				selected: false,
				drag: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Бюджет отдела',
				parents: ['Командировка'],
				hidden: false,
				type: 1,
				kind: Kind.String,
				newkind: Newkind.String,
				selected: false,
				drag: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Состояние',
				parents: ['Командировка'],
				hidden: false,
				type: 1,
				kind: Kind.Status,
				newkind: Newkind.String,
				selected: false,
				drag: true,
				children: [],
			},
			{
				id: uid(),
				text: 'Заданиe',
				parents: ['Командировка'],
				hidden: false,
				type: 1,
				kind: Kind.Link,
				newkind: Newkind.String,
				selected: false,
				drag: true,
				children: [],
			},
		],
	},
]

export { fields, operators }
