import { uid } from 'quasar'

enum Kind {
	String,
	Text,
	Date,
	Org,
	Num,
	Man,
	Status,
	Link,
	Phone,
	Email,
	Bool,
	Key,
	Goal,
}

const operators = [
	{
		id: '1',
		text: 'И',
		text1: '',
		text2: '',
		hidden: false,
		type: 0,
		selected: false,
		drag: true,
		drop: true,
		icon: 'mdi-gate-and',
		fields: [],
		synparents: [],
		syn: [],
	},
	{
		id: '2',
		text: 'ИЛИ',
		text1: '',
		text2: '',
		hidden: false,
		type: 0,
		typ: true,
		selected: false,
		drag: true,
		drop: true,
		icon: 'mdi-gate-or',
		fields: [],
		synparents: [],
		syn: [],
	},
]

const fields = [
	{
		id: uid(),
		text: 'Документ',
		hidden: false,
		type: 1,
		selected: false,
		drag: false,
		drop: false,
		open: true,
		children: [
			{
				id: uid(),
				parents: ['Документ'],
				text: 'Тема',
				type: 1,
				hidden: false,
				open: true,
				selected: false,
				drag: true,
				kind: Kind.String,
				inp: true,
				common: true,
			},
			{
				id: 'ooo',
				parents: ['Документ'],
				text: 'Номер',
				kind: Kind.Num,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				inp: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Документ'],
				text: 'Дата регистрации',
				kind: Kind.Date,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				date: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Документ'],
				text: 'Регистратор',
				kind: Kind.Man,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				man: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Документ'],
				text: 'Содержание',
				kind: Kind.Text,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				inp: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Документ'],
				text: 'Дата документа',
				kind: Kind.Date,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				date: true,
				common: true,
			},
		],
	},
	{
		id: uid(),
		text: 'Задание',
		hidden: false,
		type: 1,
		selected: false,
		drag: false,
		children: [
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Название',
				kind: Kind.String,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				inp: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Срок исполнения',
				kind: Kind.Date,
				type: 1,
				hidden: false,
				selected: false,
				drag: true,
				date: true,
				common: true,
			},
			{
				id: uid(),
				parents: ['Задание'],
				text: 'Важность',
				hidden: false,
				type: 1,
				selected: false,
				drag: true,
				common: true,
			},
		],
	},
]

export { fields, operators }