import { defineStore } from 'pinia'
import { ref } from 'vue'

export const useLogEventsStore = defineStore('logevents', () => {
	const events = ref([
		{
			id: 0,
			date: 1756447083568,
			app: 'Управление командировками',
			user: 'Роза Львовна',
			db: '--',
			event: 'Создание версии',
			result: true,
		},
		{
			id: 1,
			date: 1756445283568,
			app: 'Заявки на отпуск',
			user: 'Орлов П.С.',
			db: 'DV-Main',
			event: 'Удаление',
			result: false,
		},
		{
			id: 2,
			date: 1756443183568,
			app: 'Заявки на отпуск',
			user: 'Орлов П.С.',
			db: 'DV-Prod',
			event: 'Проверка',
			result: true,
		},
		{
			id: 3,
			date: 1756441383568,
			app: 'Служебные записки',
			user: 'Сидоров В.В.',
			db: 'DV-Test',
			event: 'Авторизация',
			result: false,
		},
		{
			id: 4,
			date: 1756438983568,
			app: 'Заявки на отпуск',
			user: 'Кузнецов Д.Д.',
			db: 'DV-Prod',
			event: 'Обновление',
			result: false,
		},
		{
			id: 5,
			date: 1756436283568,
			app: 'Служебные записки',
			user: 'Иванов И.И.',
			db: 'DV-Main',
			event: 'Удаление',
			result: true,
		},
		{
			id: 6,
			date: 1756433883568,
			app: 'Управление командировками',
			user: 'Орлов П.С.',
			db: 'DV-Test',
			event: 'Проверка',
			result: false,
		},
		{
			id: 7,
			date: 1756431783568,
			app: 'Служебные записки',
			user: 'Сидоров В.В.',
			db: 'DV-Prod',
			event: 'Авторизация',
			result: false,
		},
		{
			id: 8,
			date: 1756429983568,
			app: 'Заявки на отпуск',
			user: 'Кузнецов Д.Д.',
			db: 'DV-Main',
			event: 'Обновление',
			result: false,
		},
		{
			id: 9,
			date: 1756427583568,
			app: 'Управление командировками',
			user: 'Орлов П.С.',
			db: 'DV-Test',
			event: 'Удаление',
			result: false,
		},
		{
			id: 10,
			date: 1756425483568,
			app: 'Заявки на отпуск',
			user: 'Орлов П.С.',
			db: 'DV-Prod',
			event: 'Проверка',
			result: true,
		},
		{
			id: 11,
			date: 1756423383568,
			app: 'Служебные записки',
			user: 'Иванов И.И.',
			db: 'DV-Main',
			event: 'Авторизация',
			result: true,
		},
		{
			id: 12,
			date: 1756420983568,
			app: 'Управление командировками',
			user: 'Сидоров В.В.',
			db: 'DV-Test',
			event: 'Удаление',
			result: false,
		},
		{
			id: 13,
			date: 1756418883568,
			app: 'Служебные записки',
			user: 'Орлов П.С.',
			db: '--',
			event: 'Создание версии',
			result: true,
		},
	])

	return { events }
})
