import { uid } from 'quasar'
import { Kind } from '@/types/enum'

const zero = [
	{
		id: uid(),
		text: 'Документы',
		selected: false,
		level: 0,
		parents: [],
		children: [
			{
				id: 'Все',
				text: 'Все документы',
				selected: false,
				parents: ['Документы'],
				level: 1,
				children: [
					{
						id: uid(),
						parents: ['Документы', 'Все документы'],
						text: 'Тема',
						type: 1,
						selected: false,
						kind: Kind.String,
						level: 2,
						children: [],
					},
					{
						id: uid(),
						parents: ['Документы', 'Все документы'],
						text: 'Номер',
						kind: Kind.Num,
						type: 1,
						selected: false,
						level: 2,
						children: [],
					},
					{
						id: uid(),
						parents: ['Документы', 'Все документы'],
						text: 'Дата регистрации',
						kind: Kind.Date,
						type: 1,
						selected: false,
						level: 2,
						children: [],
					},
					{
						id: uid(),
						parents: ['Документы', 'Все документы'],
						text: 'Регистратор',
						kind: Kind.Man,
						type: 1,
						selected: false,
						level: 2,
						children: [],
					},
					{
						id: uid(),
						parents: ['Документы', 'Все документы'],
						text: 'Содержание',
						kind: Kind.Text,
						type: 1,
						selected: false,
						level: 2,
						children: [],
					},
					{
						id: uid(),
						parents: ['Документы', 'Все документы'],
						text: 'Дата документа',
						kind: Kind.Date,
						type: 1,
						selected: false,
						level: 2,
						children: [],
					},
				],
			},
			{
				id: uid(),
				text: 'Исходящий',
				selected: false,
				parents: ['Документы'],
				level: 1,
				children: [
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Тема',
						kind: Kind.String,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Номер',
						kind: Kind.Num,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Дата регистрации',
						kind: Kind.Date,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Регистратор',
						kind: Kind.Man,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Подготовил',
						kind: Kind.Man,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Содержание',
						kind: Kind.Text,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Согласующие',
						kind: Kind.Man,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Подписывают',
						kind: Kind.Man,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Получатели',
						kind: Kind.Org,
						type: 1,
						level: 2,
						selected: false,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Исходящий', 'Получатели'],
								text: 'Контактное лицо',
								kind: Kind.Man,
								type: 1,
								level: 3,
								selected: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий', 'Получатели'],
								text: 'Организация',
								kind: Kind.Org,
								type: 1,
								level: 3,
								selected: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий', 'Получатели'],
								text: 'Телефон',
								kind: Kind.Phone,
								type: 1,
								level: 3,
								selected: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Исходящий', 'Получатели'],
								text: 'Email',
								kind: Kind.Email,
								type: 1,
								level: 3,
								selected: false,
							},
						],
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Состояние',
						kind: Kind.Status,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Заданиe',
						kind: Kind.Link,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Исходящий'],
						text: 'Группа заданий',
						kind: Kind.Link,
						type: 1,
						level: 2,
						selected: false,
					},
				],
			},
			{
				id: uid(),
				text: 'Входящий',
				selected: false,
				parents: ['Документы'],
				level: 1,
				children: [
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Тема',
						kind: Kind.String,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Номер',
						kind: Kind.Num,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Дата регистрации',
						kind: Kind.Date,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Регистратор',
						kind: Kind.Man,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Содержание',
						kind: Kind.Text,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Исх.номер',
						kind: Kind.Num,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Дата документа',
						kind: Kind.Date,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Отправитель',
						kind: Kind.Org,
						type: 1,
						level: 2,
						selected: false,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Входящий', 'Отправитель'],
								text: 'Контактное лицо',
								kind: Kind.Man,
								type: 1,
								level: 3,
								selected: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий', 'Отправитель'],
								text: 'Организация',
								kind: Kind.Org,
								type: 1,
								level: 3,
								selected: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий', 'Отправитель'],
								text: 'Телефон',
								kind: Kind.Phone,
								type: 1,
								level: 3,
								selected: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Входящий', 'Отправитель'],
								text: 'Email',
								kind: Kind.Email,
								type: 1,
								level: 3,
								selected: false,
							},
						],
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Состояние',
						kind: Kind.Status,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Заданиe',
						kind: Kind.Link,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Входящий'],
						text: 'Группа заданий',
						kind: Kind.Link,
						type: 1,
						level: 2,
						selected: false,
					},
				],
			},
			{
				id: uid(),
				text: 'Договор',
				selected: false,
				parents: ['Документы'],
				level: 1,
				children: [
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Номер',
						kind: Kind.Num,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Дата регистрации',
						kind: Kind.Date,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Регистратор',
						kind: Kind.Man,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Подготовил',
						kind: Kind.Man,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Предмет договора',
						kind: Kind.Text,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Организация',
						kind: Kind.Man,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Дата документа',
						kind: Kind.Date,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Ответственный',
						kind: Kind.Man,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Подписывают',
						kind: Kind.Man,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Организация контрагент',
						kind: Kind.Org,
						type: 1,
						level: 2,
						selected: false,
						children: [
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'Контактное лицо',
								kind: Kind.Man,
								type: 1,
								level: 3,
								selected: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'Организация',
								kind: Kind.Org,
								type: 1,
								level: 3,
								selected: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'Телефон',
								kind: Kind.Phone,
								type: 1,
								level: 3,
								selected: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'Email',
								kind: Kind.Email,
								type: 1,
								level: 3,
								selected: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'ИНН',
								kind: Kind.String,
								type: 1,
								level: 3,
								selected: false,
								man: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'ОГРН',
								kind: Kind.String,
								type: 1,
								level: 3,
								selected: false,
								man: false,
							},
							{
								id: uid(),
								parents: ['Документ', 'Договор', 'Организация контрагент'],
								text: 'БИК',
								kind: Kind.String,
								type: 1,
								level: 3,
								selected: false,
								man: false,
							},
						],
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Состояние',
						kind: Kind.Status,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Заданиe',
						kind: Kind.Link,
						type: 1,
						level: 2,
						selected: false,
					},
					{
						id: uid(),
						parents: ['Документ', 'Договор'],
						text: 'Группа заданий',
						kind: Kind.Link,
						type: 1,
						level: 2,
						selected: false,
					},
				],
			},
			{
				id: uid(),
				text: 'Доп.соглашение',
				selected: false,
				parents: ['Документы'],
				level: 1,
				children: [],
			},
		],
	},
	{
		id: uid(),
		text: 'Задания',
		selected: false,
		level: 0,
		parents: [],
		children: [
			{
				id: 'Все',
				text: 'Все задания',
				selected: false,
				parents: ['Задания'],
				level: 1,
				children: [
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Название',
						kind: Kind.String,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Срок исполнения',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Дата контроля',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Дата отправки',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Автор',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
						children: [],
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Содержание',
						kind: Kind.Text,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Докумeнт',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Исполнитель',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
						children: [],
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Состояние ',
						kind: Kind.Status,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						state: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Подчиненные группы заданий',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Подчиненные задания',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Контролер',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Длительность фактическая',
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Завершено позже срока',
						kind: Kind.Bool,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						ruk: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'Все задания'],
						text: 'Задание ответственного исполнителя',
						kind: Kind.Bool,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
				],
			},
			{
				id: uid(),
				text: 'На исполнение',
				selected: false,
				parents: ['Задания'],
				level: 1,
				children: [
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Название',
						kind: Kind.String,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Срок исполнения',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Дата контроля',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Дата отправки',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Автор',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
						children: [],
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Содержание',
						kind: Kind.Text,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Докумeнт',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Исполнитель',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
						children: [],
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Состояние ',
						kind: Kind.Status,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						state: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Контролер',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Длительность фактическая',
						kind: Kind.Num,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Завершено позже срока',
						kind: Kind.Bool,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Задание ответственного исполнителя',
						kind: Kind.Bool,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Подчиненные группы заданий',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На исполнение'],
						text: 'Подчиненные задания',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
				],
			},
			{
				id: uid(),
				text: 'На ознакомление',
				selected: false,
				parents: ['Задания'],
				level: 1,
				children: [
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Название',
						kind: Kind.String,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Срок исполнения',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Дата контроля',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Дата отправки',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Автор',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
						children: [],
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Содержание',
						kind: Kind.Text,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Докумeнт',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Исполнитель',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
						children: [],
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Состояние ',
						kind: Kind.Status,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						state: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Подчиненные группы заданий',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Подчиненные задания',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Контролер',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На ознакомление'],
						text: 'Длительность фактическая',
						kind: Kind.Num,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
				],
			},
			{
				id: uid(),
				text: 'На согласование',
				selected: false,
				parents: ['Задания'],
				level: 1,
				children: [
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Название',
						kind: Kind.String,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Срок исполнения',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Дата контроля',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Дата отправки',
						kind: Kind.Date,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Автор',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
						children: [],
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Содержание',
						kind: Kind.Text,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						inp: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Докумeнт',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Исполнитель',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
						children: [],
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Состояние ',
						kind: Kind.Status,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						state: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Контролер',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Длительность фактическая',
						kind: Kind.Num,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Завершено позже срока',
						kind: Kind.Bool,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Задание ответственного исполнителя',
						kind: Kind.Bool,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Подчиненные группы заданий',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Подчиненные задания',
						kind: Kind.Link,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Инициатор',
						kind: Kind.Man,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
						common: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Этап согласования',
						kind: Kind.String,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
					{
						id: uid(),
						parents: ['Задание', 'На согласование'],
						text: 'Цикл согласования',
						kind: Kind.Num,
						level: 2,
						hidden: false,
						type: 1,
						selected: false,
						drag: true,
					},
				],
			},
		],
	},
	{
		id: uid(),
		text: 'Группа заданий',
		selected: false,
		level: 0,
		parents: [],
		children: [
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Тема',
				kind: Kind.String,
				type: 1,
				level: 1,
				selected: false,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Отправлено',
				kind: Kind.Date,
				type: 1,
				level: 1,
				selected: false,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Срок исполнения',
				kind: Kind.Date,
				type: 1,
				level: 1,
				selected: false,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Автор',
				kind: Kind.Man,
				type: 1,
				level: 1,
				selected: false,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Содержание ',
				kind: Kind.Text,
				type: 1,
				level: 1,
				selected: false,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Докумeнт',
				kind: Kind.Link,
				type: 1,
				level: 1,
				selected: false,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Исполнители',
				kind: Kind.Man,
				type: 1,
				level: 1,
				selected: false,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Состояние ',
				kind: Kind.Status,
				type: 1,
				level: 1,
				selected: false,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Подчиненные задания',
				kind: Kind.Link,
				type: 1,
				level: 1,
				selected: false,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Контролер',
				kind: Kind.Man,
				type: 1,
				level: 1,
				selected: false,
			},
			{
				id: uid(),
				parents: ['ГЗ'],
				text: 'Тип',
				type: 1,
				level: 1,
				selected: false,
			},
		],
	},
	{
		id: uid(),
		text: 'Цели',
		selected: false,
		level: 0,
		parents: [],
		children: [
			{
				id: uid(),
				text: 'Дата регистрации',
				parents: ['Цели'],
				type: 1,
				selected: false,
				kind: Kind.Date,
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'Регистратор',
				parents: ['Цели'],
				type: 1,
				selected: false,
				kind: Kind.Man,
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'Сотрудник',
				parents: ['Цели'],
				type: 1,
				selected: false,
				kind: Kind.Man,
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'Год',
				parents: ['Цели'],
				type: 1,
				kind: Kind.Num,
				selected: false,
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'Квартал',
				parents: ['Цели'],
				type: 1,
				kind: Kind.Num,
				selected: false,
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'Сумма факта',
				parents: ['Цели'],
				type: 1,
				kind: Kind.Num,
				selected: false,
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'Сумма весов',
				parents: ['Цели'],
				type: 1,
				kind: Kind.Num,
				selected: false,
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'Состояние',
				parents: ['Цели'],
				type: 1,
				kind: Kind.Status,
				selected: false,
				level: 1,
				children: [],
			},
			{
				id: uid(),
				text: 'Квартальные цели',
				parents: ['Цели'],
				type: 1,
				kind: Kind.Goal,
				selected: false,
				level: 1,
				children: [
					{
						id: uid(),
						text: 'Критерий достижения',
						parents: ['Цели', 'Квартальные цели'],
						type: 1,
						kind: Kind.String,
						selected: false,
						level: 2,
						children: [],
					},
					{
						id: uid(),
						text: 'Плановая дата выполнения',
						parents: ['Цели', 'Квартальные цели'],
						type: 1,
						kind: Kind.Date,
						selected: false,
						level: 2,
						children: [],
					},
					{
						id: uid(),
						text: 'Вес',
						parents: ['Цели', 'Квартальные цели'],
						type: 1,
						kind: Kind.Num,
						selected: false,
						level: 2,
						children: [],
					},
					{
						id: uid(),
						text: 'Факт',
						parents: ['Цели', 'Квартальные цели'],
						type: 1,
						kind: Kind.Num,
						selected: false,
						level: 2,
						children: [],
					},
				],
			},
		],
	},
	{
		id: uid(),
		text: 'Командировки',
		selected: false,
		level: 0,
		parents: [],
		children: [
			{
				id: uid(),
				text: 'Номер',
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Num,
				children: [],
			},
			{
				id: uid(),
				text: 'Дата регистрации',
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Date,
				children: [],
			},
			{
				id: uid(),
				text: 'Регистратор',
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Man,
				children: [],
			},
			{
				id: uid(),
				text: 'Командируемые',
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Man,
				children: [],
			},
			{
				id: uid(),
				text: 'Цель поездки',
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Text,
				children: [],
			},
			{
				id: uid(),
				text: 'Ответственный',
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Man,
				children: [],
			},
			{
				id: uid(),
				text: 'Дата отъезда',
				parents: ['Командировка'],
				type: 1,
				selected: false,
				kind: Kind.Date,
				children: [],
			},
			{
				id: uid(),
				text: 'Куда',
				parents: ['Командировка'],
				type: 1,
				kind: Kind.String,
				selected: false,
				children: [
					{
						id: uid(),
						text: 'Регион',
						parents: ['Командировка', 'Куда'],
						type: 1,
						kind: Kind.String,
						selected: false,
						children: [],
					},
					{
						id: uid(),
						text: 'Город',
						parents: ['Командировка', 'Куда'],
						type: 1,
						kind: Kind.String,
						selected: false,
						children: [],
					},
				],
			},
			{
				id: uid(),
				text: 'Организация',
				parents: ['Командировка'],
				type: 1,
				kind: Kind.Org,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				text: 'Бюджет отдела',
				parents: ['Командировка'],
				type: 1,
				kind: Kind.String,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				text: 'Состояние',
				parents: ['Командировка'],
				type: 1,
				kind: Kind.Status,
				selected: false,
				children: [],
			},
			{
				id: uid(),
				text: 'Заданиe',
				parents: ['Командировка'],
				type: 1,
				kind: Kind.Link,
				selected: false,
				children: [],
			},
		],
	},
]

export { zero }
